### ISSUE TITLE
Can not connect to some of the pins

### ISSUE THREAD

**Issue by RosCstr** [troelssiggaard/ESP32-fritzing-module#1]
Hello,

I saw that on your design of the chip there are some pins that I can not connect to (12 to be exact).
My question is what I can do to modify this using Fritzing program or did you have a reason which made you do this? Or could you modify the part in order for all the pins to be able to connect to?

Thanks

**Comment by Power3DPrinting** [comment]
Same Problem, File is corrupted, every time you download it you get an error, not sure how to fix

**Comment by Odi55555** [comment]
I have the same issue :(

**Comment by 1TekPro** [comment]
Pin 39 is a large ground pad. Perhaps make this connectable also.

**Comment by 1TekPro** [comment]
This issue has been resolved in the latest commit.

**Comment by troelssiggaard** [comment]
Sorry for not improving this part, thanks to 1TekPro for fixing it.
