### ISSUE TITLE
png files not valide

### ISSUE THREAD

**Issue by el-j** [troelssiggaard/ESP32-fritzing-module#4]
nice work on this thing.
sadly png files are not valide as a real fritzing part.

do you have any brd-eagle file of the wroom esp32 board?

**Comment by 1TekPro** [comment]
The png files are for reference. The actual Fritzing part is "ESP-WROOM-32 [ESP-32S] Module.fzpz".

**Comment by troelssiggaard** [comment]
Sorry, no brd-eagle, made this part a long time ago because I needed to test some stuff out. This was my first Fritzing part. PNG's are only for reference as 1TekPro pointed out.
